title: 竹叶舟
author: LotusSaverin
description: 身如不系之舟
theme: minima
markdown: kramdown
collections:
  chapters:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: chapters
    values:
      layout: chapter
      permalink: /:collection/:name/
